# Namespace 'auditty' should exist before installing the chart

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "750m"

serviceAccount:
  name: auditty-optimizer

# The secret is mandatory and can be created by the helm chart if you set create to 'true'
secret:
  create: true
  name: auditty-secret
  licenseKey: "replace-this"
  orgName: "replace-this"
  orgUnit: "ou-name"
  envName: "env-name"

# The configMap is mandatory and can be created by the helm chart if you set enabled to 'true'
configMap:
  enabled: true
  clusterName: "name-of-your-cluster"
  excludeNamespaces:
    - "kube-system"
  excludePods:
  excludeLogs:
  includeLogs:

daemonset:
  tolerations:
    - operator: "Exists"
