apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "auditty-optimizer.serviceAccountName" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "auditty-optimizer.serviceAccountName" . }}
    namespace: auditty
roleRef:
  kind: ClusterRole
  name: {{ include "auditty-optimizer.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
