{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: auditty-secret
  namespace: auditty
type: Opaque
data:
  auditty-license-key: {{ .Values.secret.licenseKey | b64enc | quote }}
  org-name: {{ .Values.secret.orgName | b64enc | quote }}
  org-unit: {{ .Values.secret.orgUnit | b64enc | quote }}
  env-name: {{ .Values.secret.envName | b64enc | quote }}
  metrics-auth-token: {{ .Values.secret.metricsAuthToken | b64enc | quote }}
{{- end }}
