apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditty-optimizer.serviceAccountName" . }}
  namespace: auditty
  labels:
    {{- include "auditty-optimizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
