name: Publish Helm Chart

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the workflow to push changes to the gh-pages branch

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.0

    # Step 3: Build the new Helm chart package
    - name: Build Helm Chart
      run: |
        helm lint ./charts/auditty-optimizer  # Validate the chart
        helm package ./charts/auditty-optimizer -d ./chart-packages  # Package into chart-packages/

    # Step 4: Clone the gh-pages Branch
    - name: Clone gh-pages Branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages

    # Step 5: Copy the New Chart and Update the Index
    - name: Update Helm Repo Index
      run: |
        mkdir -p ./charts
        mv ./chart-packages/* ./charts/ # Move the packaged chart to the charts directory
        helm repo index ./charts --url https://auditty.github.io/helm-charts
        cp ./charts/index.yaml ./index.yaml # Copy the updated index to the root directory

    # Step 6: Commit and Push Changes to gh-pages
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.yaml ./charts
        git commit -m "Publish auditty-optimizer chart [skip ci]" || echo "No changes to commit"
        git push origin gh-pages
